apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:hyeon-wooo/devdrill-gitops.git"
    targetRevision: HEAD
    path: cluster/app
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
