service:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 30080
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
      nodePort: 30443
    - port: 36030
      targetPort: 36030
      protocol: TCP
      name: mariadb-tcp
      nodePort: 36030

nginxGateway:
  replicaCount: 3

# 노드 당 Pod 1개 강제
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/instance
              operator: In
              values:
                - ngf # helm release 이름
        topologyKey: "kubernetes.io/hostname"

tolerations:
  - key: dedicated
    operator: Exists
