apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: px-pvc
  namespace: project-exhibition
spec:
  volumeName: px-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: px-storage
