apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler-store
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-auth
            key: dopplerToken
