apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-controller
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx-gateway-fabric
    repoURL: oci://ghcr.io/nginxinc/charts
    targetRevision: 1.2.0
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
