apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector-sa
  namespace: observability

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-role
rules:
  - apiGroups: [""]
    resources:
      - "pods"
      - "pods/status"
      - "namespaces"
      - "nodes"
      - "nodes/proxy"
      - "nodes/stats"
      - "nodes/metrics"
    verbs:
      - "get"
      - "watch"
      - "list"

  - apiGroups: ["apps"]
    resources:
      - "replicasets"
      - "deployments"
    verbs:
      - "get"
      - "list"
      - "watch"

  - apiGroups: ["extensions"]
    resources:
      - "replicasets"
      - "deployments"
    verbs:
      - "get"
      - "list"
      - "watch"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-role-binding
subjects:
  - kind: ServiceAccount
    name: otel-collector-sa
    namespace: observability
roleRef:
  kind: ClusterRole
  name: otel-collector-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: observability
spec:
  mode: daemonset
  image: otel/opentelemetry-collector-k8s:0.123.0

  serviceAccount: otel-collector-sa

  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  envFrom:
    - secretRef:
        name: grafana-cloud-credentials

  resources:
    limits:
      cpu: 300m
      memory: 512Mi

  nodeSelector:
    kubernetes.io/os: linux

  # host filesystem 마운트 (호스트레벨 메트릭 수집을 위해)
  volumeMounts:
    - name: hostfs
      mountPath: /hostfs
      readOnly: true

  volumes:
    - name: hostfs
      hostPath:
        path: /
        type: Directory

  #######################################################################
  # CONFIG
  #######################################################################
  config:
    extensions:
      basicauth:
        client_auth:
          username: ${env:GRAFANA_INSTANCE_ID}
          password: ${env:GRAFANA_API_KEY}
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

      kubeletstats:
        collection_interval: 30s
        auth_type: serviceAccount
        insecure_skip_verify: true
        metric_groups:
          - node
          - pod
          - container

      hostmetrics:
        root_path: /hostfs
        collection_interval: 30s
        scrapers:
          cpu: {}
          memory: {}
          disk: {}
          filesystem: {}
          network: {}

    processors:
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25

      batch:
        timeout: 5s
        send_batch_size: 2048

      batch/trace:
        timeout: 5s
        send_batch_size: 2048

      groupbytrace:
        wait_duration: 10s
        num_traces: 10000

      tail_sampling:
        decision_wait: 10s
        num_traces: 10000
        expected_new_traces_per_sec: 100
        policies:
          - name: error-traces
            type: status_code
            status_code:
              status_codes: [ERROR]
          - name: normal-traces
            type: probabilistic
            probabilistic:
              # 모든 트레이스 수집 (FIXME: 부하 걸 때는 조정할 것!!)
              sampling_percentage: 100

      k8sattributes:
        auth_type: serviceAccount
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.container.name
            - k8s.node.name

      # transform/labels:
      #   metric_statements:
      #     - context: datapoint
      #       statements:
      #         - set(attributes["k8s_pod_name"], resource.attributes["k8s.pod.name"])
      #         - set(attributes["k8s_namespace_name"], resource.attributes["k8s.namespace.name"])
      #         - set(attributes["k8s_container_name"], resource.attributes["k8s.container.name"])

    exporters:
      otlphttp/grafana:
        endpoint: https://otlp-gateway-prod-ap-northeast-0.grafana.net/otlp
        auth:
          authenticator: basicauth

      debug:
        verbosity: normal

    service:
      extensions: [basicauth]

      pipelines:
        logs:
          receivers: [otlp]
          processors: [memory_limiter, k8sattributes, batch]
          exporters: [otlphttp/grafana]

        metrics:
          receivers: [otlp, hostmetrics]
          processors: [memory_limiter, k8sattributes, batch]
          exporters: [otlphttp/grafana]

        traces:
          receivers: [otlp]
          processors:
            [
              memory_limiter,
              k8sattributes,
              groupbytrace,
              tail_sampling,
              batch/trace,
            ]
          exporters: [otlphttp/grafana]
