apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-kubelet
  namespace: observability
spec:
  mode: daemonset
  image: otel/opentelemetry-collector-k8s:0.123.0

  serviceAccount: otel-collector-sa

  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  envFrom:
    - secretRef:
        name: grafana-cloud-credentials

  resources:
    limits:
      cpu: 200m
      memory: 128Mi

  config:
    extensions:
      basicauth:
        client_auth:
          username: ${env:GRAFANA_INSTANCE_ID}
          password: ${env:GRAFANA_API_KEY}

    receivers:
      kubeletstats:
        collection_interval: 10s
        auth_type: serviceAccount
        insecure_skip_verify: true
        metric_groups:
          - node
          - pod
          - container

      prometheus/ds-collector:
        config:
          scrape_configs:
            - job_name: "ds-collector"
              scrape_interval: 10s
              static_configs:
                - targets: ["127.0.0.1:9998"]

      prometheus/node_exporter:
        config:
          scrape_configs:
            - job_name: "node-exporter"
              scrape_interval: 15s
              static_configs:
                - targets:
                    - "${env:K8S_NODE_NAME}:9100"

    processors:
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25

      batch:
        timeout: 5s
        send_batch_size: 1024

      k8sattributes:
        auth_type: serviceAccount
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.container.name
            - k8s.node.name

    exporters:
      otlphttp/grafana:
        endpoint: https://otlp-gateway-prod-ap-northeast-0.grafana.net/otlp
        auth:
          authenticator: basicauth

      debug:
        verbosity: normal

    service:
      extensions: [basicauth]

      pipelines:
        metrics/kubeletstats:
          receivers: [kubeletstats, prometheus/node_exporter]
          processors: [memory_limiter, k8sattributes, batch]
          exporters: [otlphttp/grafana]

        metrics/ds-collector:
          receivers: [prometheus/ds-collector]
          processors: [memory_limiter, k8sattributes, batch]
          exporters: [otlphttp/grafana]

      telemetry:
        metrics:
          address: "0.0.0.0:9999"
