apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: doppler-store
  namespace: devdrill-prod
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-auth
            key: dopplerToken
