apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devdrill-api-hpa
  namespace: devdrill-prod
  annotations:
    notifications.argoproj.io/subscribe.on-hpa-scaling.slack: devdrill-alert
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devdrill-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
