apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devdrill-pvc
  namespace: devdrill-prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-home
  resources:
    requests:
      storage: 100Gi
