apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubewatch
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/metrics-server/
      chart: kubewatch
      targetRevision: 3.5.0
      helm:
        valueFiles:
          - $myconfig/cluster/app/kubewatch/values.yaml
    - repoURL: "git@github.com:hyeon-wooo/devdrill-gitops.git"
      targetRevision: HEAD
      ref: myconfig
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
