rbac:
  create: false

slack:
  enabled: true
  channel: "#devdrill-alert"

# HPA 이벤트만 감시
resourcesToWatch:
  deployment: false
  horizontalpodautoscaler: true
  pod: false
  services: false

env:
  - name: KW_SLACK_TOKEN
    valueFrom:
      secretKeyRef:
        name: slack-secret
        key: slack-token

extraDeploy:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: kubewatch-event-patcher
    rules:
      - apiGroups: ["", "events.k8s.io"]
        resources: ["events"]
        verbs: ["get", "list", "watch"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: kubewatch-event-patcher-binding
    subjects:
      - kind: ServiceAccount
        name: kubewatch
        namespace: observability
    roleRef:
      kind: ClusterRole
      name: kubewatch-event-patcher
      apiGroup: rbac.authorization.k8s.io
