apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-cluster
  namespace: mariadb
spec:
  image: mariadb:10.11

  rootPasswordSecretKeyRef:
    name: mariadb-secret
    key: root-password

  # 1 Active + 1 Standby
  replicas: 2

  replication:
    enabled: true
    primary:
      podIndex: 0 # mariadb-cluster-0 pod를 Primary(Active)로 고정
      automaticFailover: true # Active 다운 시 자동으로 Standby를 마스터로 승격
    replica:
      waitPoint: after_commit # 반동기 방식으로 데이터 안정성 확보

  storage:
    size: 20Gi
    storageClassName: longhorn

  tolerations:
    - key: dedicated
      operator: Exists
