apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: devdrill-gateway
  namespace: nginx-gateway
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "api.devdrill.net"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: devdrill-tls-secret
            namespace: nginx-gateway
