apiVersion: v1
kind: Secret
metadata:
  name: github-repo-auth
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:hyeon-wooo/devdrill-gitops.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    XXXXXXXX
    -----END OPENSSH PRIVATE KEY-----
