apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-credentials
  namespace: observability
type: Opaque
data:
  GRAFANA_INSTANCE_ID: XXXXXXXX
  GRAFANA_CLOUD_OTLP_ENDPOINT: XXXXXXXX
  GRAFANA_API_KEY: XXXXXXXX
